# Generated by Django 4.0 on 2023-07-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool_name', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coolname',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='coolname',
            name='cool_name1',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coolname',
            name='cool_name2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
